---
apiVersion: v1
kind: Namespace
metadata:
  name: consul1
  labels:
    kubernetes.io/metadata.name: consul1
---
apiVersion: v1
kind: Namespace
metadata:
  name: consul0
  labels:
    kubernetes.io/metadata.name: consul0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-rollback-helm-test
  namespace: argocd
data:
  sync-rollback.sh: |-
    #!/bin/bash
    argocd login argocd-server.argocd --plaintext --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
    if ! argocd app wait --health --timeout $SYNC_TIMEOUT $ARGOCD_APPLICATION; then
      if ! argocd app terminate-op $ARGOCD_APPLICATION; then echo "no op running for $ARGOCD_APPLICATION"; fi
      argocd app set --sync-policy none $ARGOCD_APPLICATION
      argocd app set $ARGOCD_APPLICATION --revision=$(argocd app history helm-test | awk 'END{print $6}')
      argocd app set --sync-policy automated $ARGOCD_APPLICATION
    else
      argocd app set --sync-policy automated $ARGOCD_APPLICATION
    fi    
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-
  annotations:
    argocd.argoproj.io/hook: Sync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: argoproj/argocd:v2.4.4
        command: ["bash"]
        args: ["-c", "/bin/sync-rollback.sh"]
        env:
          - name: ARGOCD_APPLICATION
            value: "helm-test"
          - name: ARGOCD_CLI_VERSION
            value: "v2.4.4"
          - name: SYNC_TIMEOUT
            value: "180"
          - name: ARGOCD_USERNAME
            value: "admin"
          - name: ARGOCD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: argocd-initial-admin-secret
                key: "password"
        volumeMounts:
          - name: sync-rollback-helm-test
            mountPath: /bin/sync-rollback.sh
            readOnly: true
            subPath: sync-rollback.sh
      restartPolicy: Never
      volumes:
        - name: sync-rollback-helm-test
          configMap:
            defaultMode: 0755
            name: sync-rollback-helm-test
  backoffLimit: 0
